### ISSUE TITLE
Environment Specification

### ISSUE THREAD

**Issue by Phutoast** [ying-wen/malib#18]
For example in the class `MatrixGame` the base-code asserts the number of `agent_num` and `action_num`. Why would the user has to specify these number when it is already predefined (as an assertion)

Example,
```python
if self.game == 'coordination_0_0':
    assert self.agent_num == 2
    assert self.action_num == 2
    self.payoff[0]=[[1,-1],
                   [-1,-1]]
    self.payoff[1]=[[1,-1],
                   [-1,-1]]
```

**Comment by Phutoast** [comment]
Furthermore, we already that a method `get_game_list`, which maps the game name to `agent_num` and `action_num`. For example 

```python
@staticmethod
def get_game_list():
    return {
        'zero_sum': {'agent_num': 2, 'action_num': 2}
    }
```

**Comment by ying-wen** [comment]
This is a good question.
In a pre-defined matrix game/matrix game, the agent number is fixed. This information still required in the __init__(), because I want to keep the interfaces consistent with the other games/envs, and also want the outside (env) would explicitly know/define the agent number before instantiating an environment.
As for the action number, it is redundant in initialization, the agents are expected to know the action space and observation/state space after the environment initialization.
